name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Black-isort-Flake8-mypy
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Check formatting with Black
        run: |
          pip install black
          black --check .
      - name: Check the ordering of imports with isort
        run: |
          pip install isort
          # More info: https://timothycrosley.github.io/isort/docs/configuration/options/
          isort --check --diff .
      - name: Lint with Flake8
        run: |
          # Flake8 Rules: https://www.flake8rules.com/
          pip install flake8
          flake8 --statistics --max-line-length=120 .
      - name: Check types with mypy
        run: |
          pip install mypy
          mypy src/ctrlair
