name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Black-isort-Flake8-mypy
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy
      - name: Check formatting with Black
        run: |
          black --check .
      - name: Check the ordering of imports with isort
        run: |
          # More info: https://timothycrosley.github.io/isort/docs/configuration/options/
          isort --check --diff .
      - name: Lint with Flake8
        run: |
          # Flake8 Rules: https://www.flake8rules.com/
          flake8 --statistics --max-line-length=120 .
      - name: Check types with mypy
        run: |
          mypy src/ctrlair
